In [1]:
import numpy as np

In [2]:
# Reshape a 1D NumPy array of length 12 into a 2D array of shape (3, 4)
arr = list(range(1, 13))
np_arr = np.array(arr)
np_arr = np_arr.reshape(3, 4)
np_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# Find the minimum and maximum values in a NumPy array
min_value = np.min(arr)
max_value = np.max(arr)
print(min_value, max_value)

1 12


In [5]:
# Calculate the mean, median, and standard deviation of a given NumPy array
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)

Mean: 6.5
Median: 6.5
Standard Deviation: 3.452052529534663


In [6]:
# Extract all the odd numbers from a given NumPy array
odd_values_arr = np_arr[np_arr % 2 == 1]
odd_values_arr

array([ 1,  3,  5,  7,  9, 11])

In [8]:
"""
Task 1- Create a dataset with 10 rows and 4 columns, where one of the columns must be a salary column.
Task 2- Calculate the total revenue generated
Task 3- Find the average salary for every employee 
Task 4- Check the data types of each column in the DataFrame.
"""
import pandas as pd

# Task 1
data = {
    'Name': ['Parth', 'Prem', 'Nemil', 'Kush', 'Pradip', 'Aarsh', 'Jay', 'Saket', 'Vansh', 'Raj'],
    'Age': [20, 21, 19, 18, 20, 21, 19, 18, 20, 21],
    'Salary': [20000, 25000, 30000, 35000, 20000, 25000, 30000, 35000, 20000, 25000],
    'Department': ['IT'] * 10
}
df = pd.DataFrame(data)

# Task 2
print("Total Revenue Generated: ", df['Salary'].sum())

# Task 3
print("Average Salary: ", df['Salary'].mean())

# Task 4
print("Data Types: \n", df.dtypes)

Total Revenue Generated:  265000
Average Salary:  26500.0
Data Types: 
 Name          object
Age            int64
Salary         int64
Department    object
dtype: object


### Working on Train.csv Dataset

In [10]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [15]:
transformer = ColumnTransformer(transformers = [
    ('train1', SimpleImputer(), ['Age']),
    ('train2', StandardScaler(), ['PassengerId']),
    ('train3', OneHotEncoder(drop = 'first'), ['Sex'])
])
transformer

ColumnTransformer(transformers=[('train1', SimpleImputer(), ['Age']),
                                ('train2', StandardScaler(), ['PassengerId']),
                                ('train3', OneHotEncoder(drop='first'),
                                 ['Sex'])])

In [16]:
transformer_data=transformer.fit_transform(df)
transformer_data

array([[22.        , -1.73010796,  1.        ],
       [38.        , -1.72622007,  0.        ],
       [26.        , -1.72233219,  0.        ],
       ...,
       [29.69911765,  1.72233219,  0.        ],
       [26.        ,  1.72622007,  1.        ],
       [32.        ,  1.73010796,  1.        ]])

In [17]:
columns=['Age',"PassengerId",'Sex']
transformer_data=pd.DataFrame(transformer_data,columns=columns)
transformer_data

Age  PassengerId  Sex
0    22.000000    -1.730108  1.0
1    38.000000    -1.726220  0.0
2    26.000000    -1.722332  0.0
3    35.000000    -1.718444  0.0
4    35.000000    -1.714556  1.0
..         ...          ...  ...
886  27.000000     1.714556  1.0
887  19.000000     1.718444  0.0
888  29.699118     1.722332  0.0
889  26.000000     1.726220  1.0
890  32.000000     1.730108  1.0

[891 rows x 3 columns]